---
title: "PSF_CREONS"
format: html
---

# Présentation 

Le PSF CREONS vise à structurer un réseau coopératif et inter-institutionnel de formation pour accompagner l’évolution des outils et méthodes en sciences sociales et environnementales dans les pays des Suds,notamment autour des défis liés à la science ouverte et à l’intelligence artificielle (IA).

Partant du constat que l’environnement de l’enseignement supérieur et de la recherche au Sud, et notamment dans nos antennes (Côte d’Ivoire, Madagascar, Sénégal) est marqué par de profondes inégalités de recherche qui limitent les opportunités et la reconnaissance des chercheur·e·s locaux·ales, le Projet Structurant de Formation (PSF) propose un modèle de coopérative de recherche équitable et ouverte entre le Nord et le Sud (CREONS). Ce projet consiste à impulser l’adoption de pratiques de recherche adaptées au besoin de chacun, réellement collaboratives, inclusives, et réplicables, basée sur l’utilisation d’outils modernes de communication en temps réel, de partage et de gestion des tâches. Ces outils doivent permettre non seulement d’améliorer la coordination entre les antennes de l’UMI, mais aussi plus largement de garantir la transparence et la reproductibilité de nos recherches. Il s’agit alors de contribuer à la structuration et à l’internationalisation de formations académiques mutualisées et accessibles dans les pays du Sud. Pour se faire nous développons et expérimentons une démarche de formations adaptables aux évolutions des outils et méthodes en sciences sociales et environnementales. A travers l’application d’un protocole T2VA (Travail, Valorisation, Vérification, Accompagnement), le projet vise à démocratiser les connaissances, méthodes et outils et à pérenniser ces pratiques dans nos antennes avec approche de « formation de formateurs ».

Nous intégrons dans la mise en œuvre du projet deux axes principaux de réflexions. D’une part, en parallèle de la formation aux outils de la Science Ouverte, nous questionnons son impact réel sur la réduction des inégalités de recherche. De la même manière avec l’émergence de l’Intelligence artificielle nos réflexions portent autant sur l’appropriation technique que sur le développement de méthodes et de réflexions éthiques sur son usage. A travers nos actions de formations, il s’agit de favoriser l’autonomie des personnes formées et la capacité des institutions partenaires à actualiser, diffuser, et pérenniser ces pratiques.